name: Node PR Lint, Build and Test

on:
  # Trigger when manually run
  workflow_dispatch:

  # Trigger on pushes to `master` or `rel/*`
  push:
    branches:
      - master
      - rel/*

  # Trigger on pull requests to `master` or `rel/*`
  pull_request:
    branches:
      - master
      - rel/*

jobs:
  Build:
    # Use template from https://github.com/microsoft/vscode-azuretools/tree/main/.github/workflows
    uses: microsoft/vscode-azuretools/.github/workflows/jobs.yml@main